function LuaP_110704_420585()
	DisableQuest(OwnerID(),ture)
	PlayMotionEX(OwnerID(),ruFUSION_ACTORSTATE_CRAFTING_BEGIN,ruFUSION_ACTORSTATE_CRAFTING_LOOP)
	Sleep(20);
	PlayMotion(OwnerID(),ruFUSION_ACTORSTATE_CRAFTING_END)
	Sleep(10);
	PlayMotionEX(OwnerID(),ruFUSION_ACTORSTATE_CROUCH_BEGIN,ruFUSION_ACTORSTATE_CROUCH_LOOP)
	Sleep(20);
	playMotion(OwnerID(),ruFUSION_ACTORSTATE_CROUCH_END)
	Sleep(15);
	playMotion(OwnerID(),ruFUSION_ACTORSTATE_EMOTE_HEAD_SHAKE)
	DisableQuest(OwnerID(),false)
	Say(OwnerID(),GetString("SAY_420585_0"))
end

function LuaP_110704_420586()
	DisableQuest(OwnerID(),ture)
	PlayMotionEX(OwnerID(),ruFUSION_ACTORSTATE_CRAFTING_BEGIN,ruFUSION_ACTORSTATE_CRAFTING_LOOP)
	Sleep(20);
	PlayMotion(OwnerID(),ruFUSION_ACTORSTATE_CRAFTING_END)
	Sleep(10);
	PlayMotionEX(OwnerID(),ruFUSION_ACTORSTATE_CROUCH_BEGIN,ruFUSION_ACTORSTATE_CROUCH_LOOP)
	Sleep(20);
	playMotion(OwnerID(),ruFUSION_ACTORSTATE_CROUCH_END)
	Sleep(15);
	playMotion(OwnerID(),ruFUSION_ACTORSTATE_EMOTE_VICTORY)
	DisableQuest(OwnerID(),false)
end

function LuaP_110704_420587()
	PlayMotionEX(OwnerID(),ruFUSION_ACTORSTATE_CRAFTING_BEGIN,ruFUSION_ACTORSTATE_CRAFTING_LOOP)
	Sleep(20);
	PlayMotion(OwnerID(),ruFUSION_ACTORSTATE_CRAFTING_END)
end
